CREATE DATABASE CANTEEN;
USE CANTEEN;

CREATE TABLE CUSTOMER(
CUSTOMER_ID VARCHAR(18) PRIMARY KEY,
CUSTOMER_NAME VARCHAR(30) NOT NULL,
CUSTOMER_PHONE INT(10) NOT NULL,
CUSTOMER_EMAIL VARCHAR(30) UNIQUE NOT NULL,
CUSTOMER_COUPON VARCHAR(25),
CUSTOMER_WALLETBAL DECIMAL(6,2) NOT NULL DEFAULT 0);

CREATE TABLE VENDOR(
VENDOR_ID VARCHAR(6) PRIMARY KEY,
VENDOR_NAME VARCHAR(30) NOT NULL,
VENDOR_PHONE INT(10) NOT NULL,
VENDOR_SPECS VARCHAR(30));

CREATE TABLE MENU(
FOOD_ID VARCHAR(7) PRIMARY KEY,
FOOD_NAME VARCHAR(25) NOT NULL,
VEG_NONVEG VARCHAR(6) NOT NULL,
FOOD_PRICE DECIMAL(5,2) NOT NULL,
CALORIES DECIMAL(5,2) NOT NULL);

CREATE TABLE ORDERDETAILS(
ORDER_NO VARCHAR(35) PRIMARY KEY,
VENDOR_ID VARCHAR(6) NOT NULL,
CUSTOMER_ID VARCHAR(15) NOT NULL,
FOOD_ID VARCHAR(7) NOT NULL,
QUANTITY INT(3) NOT NULL,
ETA TIMESTAMP,
DATE_TIME TIMESTAMP,
ORDER_VALUE DECIMAL(6,2) NOT NULL,
ORDER_STATUS VARCHAR(20) NOT NULL,
ORDER_RATING DECIMAL(2,1) NOT NULL,
FOREIGN KEY(VENDOR_ID) REFERENCES VENDOR(VENDOR_ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY(FOOD_ID) REFERENCES MENU(FOOD_ID)
CONSTRAINT ORDER_RATING_CONS CHECK(ORDER_RATING BETWEEN 1.0 AND 5.0));

CREATE TABLE CUSTOMER_LOGIN(
LOGIN_MAIL VARCHAR(30) NOT NULL UNIQUE,
PASSWORD VARCHAR(20) NOT NULL,
CONSTRAINT CUSTOMER_PASSWORD_LENGTH CHECK(PASSWORD LIKE "________%"),
FOREIGN KEY (LOGIN_MAIL) REFERENCES CUSTOMER(CUSTOMER_EMAIL) ON DELETE CASCADE);

CREATE TABLE VENDOR_LOGIN(
LOGIN_ID VARCHAR(6) NOT NULL UNIQUE,
PASSWORD VARCHAR(20) NOT NULL,
CONSTRAINT VENDOR_PASSWORD_LENGTH CHECK(PASSWORD LIKE "________%"),
FOREIGN KEY (LOGIN_ID) REFERENCES VENDOR(VENDOR_ID) ON DELETE CASCADE);